### ISSUE TITLE
app_test.R: Consultas

### ISSUE THREAD

**Issue by pablotis** [pablotis/Shiny_lideres#2]
@CamilaAchuri van algunas dudas respecto al script para terminar de entender:

- [x] Por qué se arman estos objetos y no se usan los inputs$variable directo en el `filter()`? [Acá](https://github.com/pablotis/Shiny_lideres/blob/6a6713606deb38829dea4afecf318f880332b12d/app_test.R#L132) y [Acá](https://github.com/pablotis/Shiny_lideres/blob/6a6713606deb38829dea4afecf318f880332b12d/app_test.R#L133)
- [x] Por qué el `print()` [Acá](https://github.com/pablotis/Shiny_lideres/blob/6a6713606deb38829dea4afecf318f880332b12d/app_test.R#L135). Cuál es la diferencia con la llamada de df al final del reactive?

<br>

## Uso de `dstools`

- [x] @CamilaAchuri Pude correr bien el filtrado con el paquete pero al momento de la selección me sale el siguiente error que no logro descifrar:
```
Listening on http://127.0.0.1:5837
guess_date_fmt
Warning: Error in : C stack usage  15925088 is too close to the limit
  91: <Anonymous>
  90: stop
  89: value[[3L]]
  88: tryCatchOne
  87: tryCatchList
  86: tryCatch
  85: do
  84: hybrid_chain
  83: renderFunc
  82: output$test
   1: runApp
```

**Comment by CamilaAchuri** [comment]
@pablotis persiste este error?, si es asi, sube un screen de la linea que crees responsable de este error y un print de los datos que estan entrando

**Comment by pablotis** [comment]
Actualicé los paquetes que estaba usando y ya no está el error. Gracias!
